Squashed commit of the following:
commit 61c1d3e40d8fdf322c235735f2dfac0c6749be2b
Merge: 1230c95 e7a2ac7
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Sat Apr 22 01:17:29 2023 -0400

    Merge remote-tracking branch 'origin/BehaviorSHown' into autoBehave

commit 1230c95c3f23b853d793f1e27d7c393094e57f69
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Sat Apr 22 01:13:32 2023 -0400

    Auto Assign fully works!!!

commit 1599c426df97f2b9af884b8b38694941990f3255
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Sat Apr 22 01:02:09 2023 -0400

    Green Auto Works!!! Fixing Yellow and Red

commit ec9ec95dadced7e7e881966e652fb38b2bbedf0a
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Sat Apr 22 00:30:52 2023 -0400

    Assign works! Auto doesnt.

    Able to assign a behavior to horse. However auto assign only works for green color and only adds one behavior instead of all green

commit 25f11e90767f61994f7c0963d16e8d8672131897
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Fri Apr 21 23:41:23 2023 -0400

    Solved many errors, not done yet

commit 41a653b6ad5ba156d9bf3b5dae02a3e08c17f0d8
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Fri Apr 21 23:29:54 2023 -0400

    Didn't add AND statements. New error now

commit 3392df4810066ffe526b5f2a6710158856279481
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Fri Apr 21 23:26:44 2023 -0400

    Solved the error to get another one

commit 8a044ecd4cecfab1e4743530effe2558a8901a8f
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Fri Apr 21 23:05:55 2023 -0400

    Progress

    Realized createhorse.php doesn't use the addHorse function in horsedb.php but instead just inserts it in the createhorse.php via an sql insert statement.

    Thus, Im adding a call to autoAssignBehavior after the insert statement there and am debugging things now

commit e7a2ac77cef079c291976528658d02e298b581d5
Author: bford-1 <94128354+bford-1@users.noreply.github.com>
Date:   Fri Apr 21 20:15:53 2023 -0400

    It displays the behaviors

    I think it works

commit fc7b54e7fcb311a81eed44f9e84ec833505d48a6
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Fri Apr 21 20:15:52 2023 -0400

    Recent changes, but nothing changed....

commit 0bc864b7079ea82d6506ff0aed2565e0d263fc72
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Fri Apr 21 19:57:18 2023 -0400

    more typos, no assignments

commit 8bc200ac42e400a1d980481b2a7069c6478ed87b
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Fri Apr 21 19:42:07 2023 -0400

    caught a typo (didn't fix the current issue tho)

commit 6233589b21dd613dfe0e84f22a807b8167e4d37f
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Fri Apr 21 19:05:44 2023 -0400

    bug fixed!

commit 7916813c365e2ef6d8d162daad100a6b9df5cc1b
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Fri Apr 21 02:48:54 2023 -0400

    New error

commit c97ee9a8d345b86dcd485f8b2d660a5b6c2bd04f
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Fri Apr 21 02:46:18 2023 -0400

    Haven't figured out the sql connect error

commit ce70afe3c1c95ada93644c79f6c767c3bf7dd7cd
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Fri Apr 21 00:23:51 2023 -0400

    Many bugs killed, but not all

    Fatal error: Cannot redeclare connect() (previously declared in D:\Comp Sci\X-Men\htdocs\horse\horsefarm2\database\dbinfo.php:21) in D:\Comp Sci\X-Men\htdocs\horse\horsefarm2\database\dbinfo.php on line 20

commit 09925457c883f4b4d0544507fdc3cdb3532e77fe
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Thu Apr 20 23:37:56 2023 -0400

    added assignedBehaviors array to be used later

commit 92e9c8e918b32896a967580260983ac546c54fee
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Thu Apr 20 23:37:11 2023 -0400

    Added assignedbehaviors array for horseprofile

commit 27c027e12aac18f7b5543f71d2e48290cf95a18b
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Thu Apr 20 23:00:32 2023 -0400

    readded assign and unassign. Created mock behaviors

commit 3f0f507382703f378faa7f5a1daa97fb2d3af47f
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Thu Apr 20 22:23:07 2023 -0400

    Update homebasedb.sql

commit 4a8028034bd3459d2035aa0049ebe23cbeb1459a
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Wed Apr 19 01:31:35 2023 -0400

    Bug fixes and syntax corrections

commit f78f97d5bfef0974613c2e065ba1027cbcbab429
Author: Nicolas Guzzone <125775407+nguzz1@users.noreply.github.com>
Date:   Tue Apr 18 10:54:24 2023 -0400

    added function calls. Need to test